task4Web/Models/ErrorViewModel.cs
namespace task4Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

task4Web/Models/UsersCreateAccountModel.cs
using System.ComponentModel.DataAnnotations;

namespace task4Web.Models
{
    public class UsersCreateAccountModel
    {
        [Required(ErrorMessage = "[The Name is obligatory]")]
        public string userName { get; set; }
        [Required(ErrorMessage = "[The password is obligatory]")]
        public string hashPassword { get; set; }
        [Required(ErrorMessage = "[The email is obligatory]")]
        public string email { get; set; }
    }
}

task4Web/Models/UsersLogInModel.cs
using System.ComponentModel.DataAnnotations;

namespace task4Web.Models
{
    public class UsersLogInModel
    {
       
        [Required(ErrorMessage = "[The email is obligatory]")]
        public string email { get; set; }
        [Required(ErrorMessage = "[The password is obligatory]")]
        public string password { get; set; }
    }
}

task4Web/Models/UsersModels.cs
using System.ComponentModel.DataAnnotations;

namespace task4Web.Models
{
    public class UsersModels
    {
        public int id { get; set; }
        public string userName {  get; set; }
        [Required(ErrorMessage = "The password is obligatory.")]      
        public string hashPassword { get; set; }
        [Required(ErrorMessage = "The email is obligatory.")]
        public string email { get; set; }
        public string lastDate { get; set; }
        public string lastHour { get; set; }
        public string userState { get; set; }

    }
}

task4Web/Controllers/AppController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using task4Web.Models;
using System.Text.Json;
using System.Text;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using static System.Runtime.InteropServices.JavaScript.JSType;
using SHA3.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace task4Web.Controllers
{

    public class AppController : Controller
    {
        public readonly HttpClient _httpClient;
     
        public AppController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://www.task4api.somee.com/");
        }
        public string encryptPassword(string password)
        {
            byte[] bytes = Encoding.UTF8.GetBytes(password);
            byte[] hash = Sha3.Sha3256().ComputeHash(bytes);
            string hashHex = BitConverter.ToString(hash).Replace("-", "").ToLowerInvariant();
            return hashHex;
        }
        public async void generateAutentication(string emailUser)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name,  emailUser)
            };
            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));

        }

        public async Task<IEnumerable<UsersModels>> listUsers()
        {
            var response = await _httpClient.GetAsync("api/Users/ListUsers");
            if (response.IsSuccessStatusCode)
                return JsonConvert.DeserializeObject<IEnumerable<UsersModels>>(await response.Content.ReadAsStringAsync());    
            return new List<UsersModels>();
        }
  
        public async Task<IActionResult> CreateUser(UsersCreateAccountModel user)
        {
            if(ModelState.IsValid)
            {
                user.hashPassword = encryptPassword(user.hashPassword);
                var content = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync("api/Users/CreateUser", content);
                if (response.IsSuccessStatusCode)
                    return View("LogIn");
                ModelState.AddModelError("Email", "[This email already exist]");
            }
            return View("CreateAccount");
        }
        public async Task<IActionResult> VerifyPassword(UsersLogInModel users)
        {
            if (ModelState.IsValid)
            {
                var responseEmail = await _httpClient.GetAsync("api/Users/ReturnHash?email="+ users.email);
                var userEmail = await responseEmail.Content.ReadAsStringAsync();
                if (responseEmail.IsSuccessStatusCode && userEmail != "")
                {
                    var hashStore = await responseEmail.Content.ReadAsStringAsync();
                    var hashCurrent = encryptPassword(users.password);
                    if (hashCurrent == hashStore)
                    {
                        var responseState = await _httpClient.GetAsync("api/Users/ValidateUserState?email=" + users.email);
                        var userBlocked = await responseState.Content.ReadAsStringAsync();
                        if (responseState.IsSuccessStatusCode && userBlocked == "false")
                        {
                            generateAutentication(users.email);
                            var contenidoState = new StringContent(JsonConvert.SerializeObject(users.email), Encoding.UTF8, "application/json");
                            await _httpClient.PostAsync("api/Users/UpdateUsers?email=", contenidoState);
                            return View("Admin", await listUsers());
                        }
                        ModelState.AddModelError("Email", "[This email is blocked]");
                    }
                    else
                        ModelState.AddModelError("Password", "[Wrong password]");
                }
                else
                    ModelState.AddModelError("Email", "[The email does not exist]");
              
            }
            return View("LogIn");
        }
        [Authorize]
        public async Task<IActionResult> Admin()
        {
            var response = await _httpClient.GetAsync("api/Users/ValidateUserState?email=" + User.FindFirst(ClaimTypes.Name)?.Value); 
            if (response.IsSuccessStatusCode)
            {
                var userDatabase = await response.Content.ReadAsStringAsync();
                if(userDatabase != "")
                {
                    if(userDatabase == "false")
                        return View("Admin", await listUsers());
                    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                }
            }
            return View("LogIn"); 
        }
        public IActionResult CreateAccount()
        {
            return View(); 
        }
        public IActionResult LogIn()
        {

            return View();
        }
        
        public async Task<IActionResult> GoBack()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View("LogIn");
        }



    }
}

task4Web/Views/App/Admin.cshtml
@model IEnumerable<UsersModels>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Tabla con 5 columnas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Admin.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/task4Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="appTitle">
        <h1>TASK 4 APP</h1>
    </div>
    <div class="toolbarContainer">
        <label class="toolbarTitle">Toolbar</label>
        <div class="toolbar">

            <button onclick="deleteUsers()"><img src="~/trash.png" title="delete users" />   </button>
            <button onclick="blockUsers()"><img src="~/block.png" title="block users" /></button>
            <button onclick="unblockUsers()"><img src="~/unblock.png" title="unblock users" /></button>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead >
                <tr>
                    <th class="bg-dark text-white"><input type="checkbox" onchange="unselectSelectAll(this)" class="seleccionarLider"></th>
                    <th id="col-id"  class="bg-dark text-white">@Html.DisplayNameFor(model => model.id)</th>
                    <th class="bg-dark text-white">@Html.DisplayNameFor(model => model.userName)</th>
                    <th class="bg-dark text-white">@Html.DisplayNameFor(model => model.email)L</th>
                    <th class="bg-dark text-white">@Html.DisplayNameFor(model => model.lastDate)</th>
                    <th id="col-lasthour" class="bg-dark text-white">@Html.DisplayNameFor(model => model.lastHour)</th>
                    <th class="bg-dark text-white">Blocked</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td> <input type="checkbox" class="seleccionar"></td>
                        <td id="col-id"> @Html.DisplayFor(modelItem => item.id)</td>
                        <td> @Html.DisplayFor(modelItem => item.userName)</td>
                        <td> @Html.DisplayFor(modelItem => item.email)</td>
                        <td> @Html.DisplayFor(modelItem => item.lastDate)</td>
                        <td id="col-lasthour"> @Html.DisplayFor(modelItem => item.lastHour)</td>
                        <td> @Html.DisplayFor(modelItem => item.userState)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>


    <script src="~/js/site.js"></script>
</body>
</html>

task4Web/Views/App/CreateAccount.cshtml
@model UsersCreateAccountModel
@{
    ViewData["Title"] = "";
}
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/CreateAccount.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/task4Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="con">
    <div class="card">
            <h1>THE TASK 4</h1>
            <h3>- CREATE USER - </h3>
            <label></label>
            <form asp-action="CreateUser" method="post">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input asp-for="userName" class="form-control" type="text" id="name" placeholder="Enter your name">
                </div>

                <div class="form-group">
                    <label for="email">E-mail  <span asp-validation-for="email" class="text-danger"></span></label>
                    <input asp-for="email" class="form-control" type="email" id="email" placeholder="Enter your email">
                   
                </div>

                <div class="form-group">
                    <label for="password">Password <span asp-validation-for="hashPassword" class="text-danger"></span></label>
                    <input asp-for="hashPassword" class="form-control" type="password" id="password" placeholder="Enter your password">
                    
                </div>

                <div>
                    <button type="submit" class="btn btn-success w-100">
                        Create!
                    </button>
                </div>
            </form>

        <div class="login-text">
             <a asp-controller="App" asp-action="LogIn">You have an account already? Log In</a>
        </div>
    </div>
            
</div>


</body>

task4Web/Views/App/LogIn.cshtml
@model UsersLogInModel
@{
    ViewData["Title"] = "";
}
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/LogIn.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/task4Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="con">
        <div class="card">
            <h1>THE TASK 4</h1>
            <h3>- LOG IN - </h3>
            <label></label>
            <form asp-action="VerifyPassword" method="post">
                <div class="form-group">
                    <label for="email">E-mail <span asp-validation-for="email" class="text-danger"></span></label>
                    <input asp-for="email" class="form-control"  type="email" placeholder="Enter your email">
                    
                </div>

                <div class="form-group">
                    <label for="password">Password  <span asp-validation-for="password" class="text-danger"></span></label>
                    <input asp-for="password" class="form-control" type="password" id="password" placeholder="Enter your password">
                   
                </div>
                <div>
                    <button type="submit" class="btn btn-success w-100">
                        Log In!
                    </button>
                </div>
            </form>
            <div class="login-text">
                <a asp-controller="App" asp-action="CreateAccount">You dont have an account? get a account</a>
            </div>
        </div>

    </div>
</body>

task4Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - task4Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/CreateAccount.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/task4Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <!--
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">task4Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>-->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!--
    <footer class="border-top footer text-muted">
        
        <div class="container">
            &copy; 2025 - task4Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>